### ISSUE TITLE
Dumping an alternative implementation here

### ISSUE THREAD

**Issue by tvoeroes** [jrgfogh/synchronized_value#3]
Hello, I saw your presentation at CppCon about this library. I'm just going to post an alternative implementation of this concept here. This is an implementation from me. Feel free to take inspiration from it. There are "shared" and "recursive" variants. "shared" supports multi reader, "recursive" supports recursive locking.
[Guard.txt](https://github.com/jrgfogh/synchronized_value/files/15083301/Guard.txt)

Sample usage:
```C++
SharedGuard<float> var{ 0.0f };

// writer:
{
	auto v = var.ReadAndWrite();
	*v = 10.0f;
	// still exclusively locked
	*v = 12.0f;
}
// reader:
{
	auto v = var.ReadOnly();
	std::cout << *v << std::endl;
	// still share-locked
	std::cout << *v << std::endl;
}
```

**Comment by jrgfogh** [comment]
Thanks!

If you have a repo with your library somewhere, I will add a link to the "related work" section of the readme.

It seems that a lot of people have had this idea independently, which is always a good sign.

I  actually like your approach better than the one I have implemented, which is the one proposed for the standard. Facebook's Folly library works similarly to yours.

**Comment by jrgfogh** [comment]
I think it is better than the alternative, which is to have an arrow operator directly on synchronized_value. It is very easy to write code like

    data->x = 5;
    data->y = 7;

and not notice that the assignments happen under separate locks. With the longer notation this bug would be immediately visible.

In any case, it's a good sign that you often lock for a single statement. That means you are keeping your lock lifetimes short.
